### ISSUE TITLE
Verve.cash System

### ISSUE THREAD

**Issue by compumatrix** [compumatrix/projects#10]
Logo for Verve
Landing Page UI/UX Prototype

**Comment by arjosephgan** [comment]
Verve Logo

![logo](https://user-images.githubusercontent.com/36975393/44617700-2b51a100-a89a-11e8-9655-a5e56081f421.png)

**Comment by pgt2rs** [comment]
Just an Idea for the Logo, using your original and adjusting it. Obviously a bit crude, but I don't have the proper program to refine it. Cheers.
![verve logo 1](https://user-images.githubusercontent.com/37249250/49085021-09601580-f21f-11e8-8d36-9cdf62387958.jpg)
