### ISSUE TITLE
UI/UX for Bitpal International

### ISSUE THREAD

**Issue by compumatrix** [compumatrix/projects#6]
Prototype Design : Joseph
HTML: John

Upload finished file here.

**Comment by arjosephgan** [comment]
Landing Page Design

![landing](https://user-images.githubusercontent.com/36975393/44510473-5ba50e00-a6e7-11e8-9e5e-00712d4c270f.png)

**Comment by arjosephgan** [comment]
Logo Design

![logo](https://user-images.githubusercontent.com/36975393/44511191-4a5d0100-a6e9-11e8-8b1b-0a3e072084a5.png)
